version: '3'

tasks:
  build:
    desc: "Builds the capargo binary executable"
    vars:
      BUILDTIME: '{{default "now" .BUILDTIME}}'
      REVISION: '{{default "local" .REVISION}}'
      VERSION: '{{default "dev" .VERSION}}'
    cmds:
    - |
      CGO_ENABLED=0 go build \
        -ldflags="-s \
        -X main.Version={{.VERSION}} \
        -X main.BuildTime={{.BUILDTIME}} \
        -X main.Revision={{.REVISION}}" \
        -o bin/capargo cmd/capargo/main.go
  build-image:
    desc: "Builds the capargo image"
    vars:
      BUILDTIME:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
      REVISION:
        sh: git rev-parse --short HEAD
      REGISTRY: '{{default "localhost:5001/superorbital" .REGISTRY}}'
      VERSION: '{{default "local" .VERSION}}'
    cmds:
    - |
      docker buildx build \
        --tag {{.REGISTRY}}/capargo:{{.VERSION}} \
        --load . \
        --build-arg="VERSION={{.VERSION}}" \
        --build-arg="BUILDTIME={{.BUILDTIME}}" \
        --build-arg="REVISION={{.REVISION}}"
  # test:
  # install:
